name: Daily

on:
  push:
  schedule:
    # Execute CI at every 5th minute
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get Covid data
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM ops
      shell: bash
      run: |
        yarn
        yarn start
      env:
        CI: true
        MSISDN_RECEIVERS_DELIMITED_WITH_SEMICOLON: ${{ secrets.MSISDN_RECEIVERS_DELIMITED_WITH_SEMICOLON }}
        MSISDN_SENDER: ${{ secrets.MSISDN_SENDER }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: sms
        path: sms.txt
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add previous.json
        git diff-index --quiet HEAD || git commit -m "Add [skip-ci]"
        git push